### ISSUE TITLE
Request: Support escaped brackets

### ISSUE THREAD

**Issue by rwejdling** [dahlia/markdown-gfm-admonition#1]
Thanks for a great extension! We're currently testing it out with our mkdocs setup using the materials theme, which renders it nicely.

Our challenge is that we're using [mdformat](https://github.com/executablebooks/mdformat) as a pre-commit hook, which escapes the brackets (`> [!NOTE]` -> `> \[!NOTE\]`).

It works fine in Github render (so devs don't notice). Would it be possible to add this to the [pattern](https://github.com/dahlia/markdown-gfm-admonition/blob/main/markdown_gfm_admonition.py#L26) as well?

Example with escaped brackets:

```markdown
> \[!NOTE\]
> this is a note
```

> \[!NOTE\]
> this is a note

**Comment by rwejdling** [comment]
Proposal:
```python
    PATTERN = re.compile(r"""
        ^ \s*
        \\?\[ ! ( NOTE | TIP | IMPORTANT | WARNING | CAUTION ) \\?\]
        (?: $ | (?: [ ] [ ] )? \n )
    """, re.VERBOSE)
```

**Comment by dahlia** [comment]
[Version 0.1.1](https://pypi.org/project/markdown-gfm-admonition/0.1.1/) released.
